### ISSUE TITLE
fails to compile on freebsd 14-current

### ISSUE THREAD

**Issue by justfly1111** [j0ru/kickoff#10]
Compiling wayland-commons v0.28.6
   Compiling wayland-commons v0.29.4
   Compiling jpeg-decoder v0.1.22
   Compiling tiff v0.6.1
   Compiling wayland-cursor v0.28.6
   Compiling thiserror-impl v1.0.30
   Compiling futures-macro v0.3.19
   Compiling enumflags2_derive v0.6.4
   Compiling serde_repr v0.1.7
   Compiling derivative v2.2.0
   Compiling tokio-macros v1.7.0
   Compiling image v0.23.14
   Compiling wayland-cursor v0.29.4
   Compiling tokio v1.15.0
   Compiling thiserror v1.0.30
   Compiling futures-executor v0.3.19
   Compiling futures v0.3.19
   Compiling smithay-client-toolkit v0.14.0
   Compiling smithay-clipboard v0.6.5
   Compiling enumflags2 v0.6.4
   Compiling toml v0.5.8
   Compiling proc-macro-crate v1.1.0
   Compiling proc-macro-crate v0.1.5
   Compiling zvariant_derive v2.10.0
   Compiling zbus_macros v1.9.2
   Compiling zvariant v2.10.0
   Compiling zbus v1.9.2
error[E0432]: unresolved import `nix::sys::socket::sockopt::PeerCredentials`
   --> /home/buckbucks/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-1.9.2/src/connection.rs:163:44
    |
163 |         use nix::sys::socket::{getsockopt, sockopt::PeerCredentials};
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ no `PeerCredentials` in `sys::socket::sockopt`

error[E0432]: unresolved import `nix::sys::socket::sockopt::PeerCredentials`
   --> /home/buckbucks/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-1.9.2/src/azync/connection.rs:180:44
    |
180 |         use nix::sys::socket::{getsockopt, sockopt::PeerCredentials};
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^ no `PeerCredentials` in `sys::socket::sockopt`

For more information about this error, try `rustc --explain E0432`.
error: failed to compile `kickoff v0.4.5`, intermediate artifacts can be found at `/tmp/cargo-installzgmK7Q`

Caused by:
  could not compile `zbus` due to 2 previous errors

error on cargo install

**Comment by j0ru** [comment]
Hey, thanks for the report!
To be honest I didn't even know FreeBSD had Wayland support ready. I think I'll spin up a vm and tinker with it a bit!
Do you have a good recomendation where I could get started with FreeBSD, I never had the pleasure before ^^

**Comment by jbeich** [comment]
> error[E0432]: unresolved import nix::sys::socket::sockopt::PeerCredentials

zbus < 2.0.0-beta.4 doesn't support non-Linux. If you can't upgrade yet try [patching the crates](https://github.com/freebsd/freebsd-ports/blob/5b78e25e4b82/shells/starship/files/patch-zbus).

**Comment by koobs** [comment]
> Hey, thanks for the report!
> 
> To be honest I didn't even know FreeBSD had Wayland support ready. I think I'll spin up a vm and tinker with it a bit!
> 
> Do you have a good recomendation where I could get started with FreeBSD, I never had the pleasure before ^^

Hit us up on #freebsd Libera IRC or our FreeBSD Discord (invite on wiki page first search result)

Happy to get you acquainted and ramped up :)

Via: https://twitter.com/l33tname/status/1485144307342483458?s=21

**Comment by j0ru** [comment]
Okay, with a bit (a lot) of time I got a virtualized FreeBSD instance with sway up and running and managed to compile and use kickoff. Unfortunately this was archived by putting the notification feature behind an compile flag. 15b5402d0e520c391f3306722a2ca4f8cd606f2b

If someone who has more experience with FreeBSD desktops and the notification stack, feel free to implement this! Now that I have a method of testing it, I'm happy to keep FreeBSD support.

**Comment by j0ru** [comment]
I noticed that including `servo-fontconfig-sys` complicates compiling on FreeBSD.
I constantly got an Error from the make call, complaining that `-j` has to be a positiv integer. I don't know if I'm alone with this problem, but after I spend more time than I want to admit trying to fix it, I switched fontconfig libraries. 
I found out that the problem is somewhat related to the jobserver, but if someone knows more I'd like to learn what the problem was!

Cheers
Joru

**Comment by jbeich** [comment]
> `servo-fontconfig-sys` complicates compiling on FreeBSD.

In FreeBSD packages `servo-fontconfig-sys` is used without issues by alacritty, cast2gif and wmfocus. Are you trying to build bundled fontconfig? If so maybe system fontconfig auto-detection failed due to missing `pkg-config` which is part of `pkgconf` package?

> complaining that `-j` has to be a positiv integer

[make(1)](https://man.freebsd.org/make/1) from base system on BSDs is not a GNU make, so often you need to invoke `gmake` (after installing from packages) instead of `make`. autotools doesn't require GNU make in simple projects while complex ones often support `export MAKE=gmake`. CMake works fine with BSD `make`.

**Comment by jbeich** [comment]
> feel free to implement this

The support will come for free if you update `zbus` crate to 2.0 or later.

**Comment by jbeich** [comment]
Ah, this project doesn't use `zbus` directly but relies on `notify-rust` whene updating to 2.0 hasn't happened yet, see https://github.com/hoodie/notify-rust/pull/131

**Comment by j0ru** [comment]
Damn, your right. With those installed it works perfectly. Nonetheless, the move to the `fontconfig` crate got rid of some dependencies and `fontconfig` is usually installed on systems that would run kickoff.
At the moment `zbus` is importetd by `notify-rust`, I'll try to get it fixed upstream

**Comment by jbeich** [comment]
Thanks, [packaged](https://www.freshports.org/x11/kickoff) (binary is [still building](http://beefy16.nyi.freebsd.org/build.html?mastername=130amd64-default&build=4970d39a547c)).
