### ISSUE TITLE
Unable to run on latest sway git version

### ISSUE THREAD

**Issue by TheDelus** [j0ru/kickoff#104]
```
$ kickoff --version
kickoff 0.7.0
```
OS: Linux/NixOS, Wayland, sway-git-bb91b7f5fa7fddb582b8dddf208cc335d39da9e7

When trying to run kickoff it crashes with 

```
$ kickoff
interface 'wl_surface' has no event 2
warning: queue 0x7f4f18000ca0 destroyed while proxies still attached:
  wl_registry@20 still attached
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 14, kind: Uncategorized, message: "Bad address" }', src/main.rs:387:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue 0x55d9769b1110 destroyed while proxies still attached:
  wl_keyboard@19 still attached
  wl_pointer@18 still attached
  zwlr_layer_surface_v1@17 still attached
  wl_surface@16 still attached
  wl_shm_pool@15 still attached
  wl_shm_pool@14 still attached
  zwp_primary_selection_device_v1@13 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@12 still attached
  wl_output@11 still attached
  wl_output@10 still attached
  wl_seat@9 still attached
  zwlr_layer_shell_v1@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```

The `interface 'wl_surface' has no event 2` error surfaces recently in quite some applications like here: https://github.com/alacritty/alacritty/issues/7083

The author of this issue suspects that this is the cause for the problem: https://github.com/swaywm/sway/commit/fc16fb65491bda0d059b8c9aeae3dc9962e5c690

**Comment by j0ru** [comment]
Thanks for the research!
Unfortunately this will take a bit to fix, since I'm currently stuck on an older version of
the library that interacts with wayland (they did some MAJOR api changes and I have to rewrite half of my codebase).

**Comment by TheDelus** [comment]
No worries. I just stick to an older version of sway now. 
Thank you so much for your work. For me its the best native wayland launcher.

**Comment by j0ru** [comment]
Thanks for the nice words :blush: 

I just finished switching to a recent version of sctk, which fixes the problem.
Feel free to test it from the `kickoff-next` branch.
