### ISSUE TITLE
Prevent Multiple Instances

### ISSUE THREAD

**Issue by Oliver-Fish** [j0ru/kickoff#13]
It would be great if I could prevent instances of kickoff from stacking on top of each other, ideally if kickoff is already open I would not like another instance to be launchable.

I can of course write a script to do this with a lock file, however, is this something you would consider natively supporting?

**Comment by j0ru** [comment]
Absolutely! It's a problem I've known about, but was too lazy too fix ^^
The canonical method seems to write your pid into $XDG_RUNTIME_DIR/<app>.pid
and check on startup if there is a pid file and if so, to check if the pid still exists.
