### ISSUE TITLE
Error when running electron apps through kickoff

### ISSUE THREAD

**Issue by tjaartvdwalt** [j0ru/kickoff#168]
Hi,

I don't know if this is a kickoff issue, but when I launch an electron application with kickoff, I get an error similar to the one below. When I launch the app directly from the terminal, I don't get the error. 

I have observed this with several apps: proton-mail, discord, android-messenger. 

![screenshot-2024-08-26-090518](https://github.com/user-attachments/assets/71665718-8f19-4ce1-a4bc-057f7be480d8)

**Comment by j0ru** [comment]
Hm, do you setup any Wayland specific environment variables in your bash profile or bashrc (or the equivalent in the shell you are using)?

**Comment by j0ru** [comment]
Kickoff just performs a standard fork, which should preserve the environment of your window manager.
Sorry in advance, my answer have, and will be a bit sporadic over the next few days/weeks because I'm currently in the process of moving country

**Comment by tjaartvdwalt** [comment]
Thanks for replying.

After some more observation, I don't think it is a kickoff problem. The same issue happens if I start the app on my laptop, then close the lid to suspend, and then open it up again.

Sorry for the wild goose chase!
