### ISSUE TITLE
Fallback Fonts

### ISSUE THREAD

**Issue by PandorasFox** [j0ru/kickoff#19]
This is an incredibly minor issue (pretty much just because of aesthetics, e.g. wanting a symbol for the prompt char that's not in the text-font being used), but it looks like font.rs only supports one font (and it looks like refactoring this for fallback fonting would be pretty involved).

Some possible hacks here:
* having a separate (optional?) `prompt_font` config value that's used when present
* allowing `font` to be a list of fontnames, iterate through fonts in order if a glyph is not present
* using built-in fontconfig `list_fonts` to do auto-fallback (probably gross and inelegant, but 'correct')

**Comment by j0ru** [comment]
Touching that code again was *interesting*, but in the end I got it working. The `font` option as been replaced by `fonts` which has to be a list of fonts. To not break compatibility the `font` Option is still present and will be handled as if it was the first font in the `fonts` list.

Have fun using it!

**Comment by PandorasFox** [comment]
o: Thank you so much!!
