### ISSUE TITLE
Kickoff fails to build when using Paru

### ISSUE THREAD

**Issue by thielblz** [j0ru/kickoff#29]
Hey there!
When trying to update to kickoff-0.5.1-1 with the AUR helper Paru I get the following error:
<code>
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
   --> /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-2.3.0/src/object_server.rs:464:10
    |
464 |     ) -> Result<bool>
    |              ^^^^^^^^^^^^
    |
note: hidden type `impl futures_core::Future` captures lifetime smaller than the function body
   --> /home/lorenz/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-2.3.0/src/object_server.rs:464:10
    |
464 |     ) -> Result<bool>
    |               ^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0700`.
error: could not compile `zbus` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'kickoff-0.5.1-1':
error: packages failed to build: kickoff-0.5.1-1
</code>

**Comment by j0ru** [comment]
Hey!
Could you check if your rust version is at least 1.58.0? `rustc --version`
If not you can update your rust version with `rustup update`

With the release of 0.5.1 I updated all the dependencies and zbus seems to be using some newer rust features

**Comment by j0ru** [comment]
I'm marking this as done, due to the lack of activity
