### ISSUE TITLE
Support more applicatoin sources

### ISSUE THREAD

**Issue by ldelossa** [j0ru/kickoff#3]
Hey there,

Your launcher is one of the best looking. Really like it.

The only issue is it doesn't find 90% of my apps. 

Apps installed with .desktop files aren't discovered, whch would be almost all apps installed via FlatPak.

**Comment by j0ru** [comment]
Hey,
thanks for your feedback! Tbh flatpaks weren't really on my radar, but I'm currently reworking the application discovery and execution interface and will keep your suggestion in mind!

**Comment by ldelossa** [comment]
Cool. Pretty sure if .desktop apps become searchable, flatpak installed apps will just work

**Comment by EinarasGar** [comment]
+1 for desktop file support. I cannot launch certain programs which requires flags on wayland to open (such as vscode). Desktop files support or some kind of config file where I could define flags for certain apps would be very good as this is a beautiful launcher! I'd contribute, but as I can understand you have a vision in mind on how exactly you want to do the implementation, so I'd rather just wait :)

**Comment by j0ru** [comment]
Nothing bad about beeing a bit lazy ^^
Kickoff already has a kind of support for dot-desktop files via the stdin parsing.
After a few people kept asking, I implement a parser, that turns the desktop files into the stdin format for kickoff which you can find [here](https://github.com/j0ru/kickoff-dot-desktop).

**Comment by dvdsk** [comment]
ahhh that is perfect this fits well into my sway config: `kickoff-dot-desktop | kickoff --from-stdin`

Thanks a lot for building that parser!

**Comment by j0ru** [comment]
No problem ;)
