### ISSUE TITLE
Panic on Result::unwrap() at src/main.rs:320

### ISSUE THREAD

**Issue by andrei-pavel** [j0ru/kickoff#48]
```console
$ RUST_BACKTRACE=full kickoff
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/main.rs:320:46
stack backtrace:
   0:     0x561fd25bfc10 - <unknown>
   1:     0x561fd2429d8e - <unknown>
   2:     0x561fd259b9f4 - <unknown>
   3:     0x561fd25c0b83 - <unknown>
   4:     0x561fd25c1abd - <unknown>
   5:     0x561fd25c1682 - <unknown>
   6:     0x561fd25c15ec - <unknown>
   7:     0x561fd25c15c1 - <unknown>
   8:     0x561fd2380362 - <unknown>
   9:     0x561fd23805e2 - <unknown>
  10:     0x561fd23bd23a - <unknown>
  11:     0x561fd239f7e4 - <unknown>
  12:     0x561fd2486014 - <unknown>
  13:     0x561fd2495741 - <unknown>
  14:     0x561fd2457d83 - <unknown>
  15:     0x561fd24940e7 - <unknown>
  16:     0x7f2b90029290 - <unknown>
  17:     0x7f2b9002934a - __libc_start_main
  18:     0x561fd23939e5 - <unknown>
  19:                0x0 - <unknown>
EXIT 101
```
```console
$ kickoff --version
kickoff 0.5.1
EXIT 0
```
Running Plasma Wayland
```console
$ pacman -Ss plasma wayland | grep installed
extra/kwayland-integration 5.25.5-1 (plasma) [installed]
extra/layer-shell-qt 5.25.5-1 (plasma) [installed]
extra/plasma-wayland-protocols 1.8.0-1 [installed]
extra/plasma-wayland-session 5.25.5-2 [installed]
EXIT 0
```

**Comment by j0ru** [comment]
Sorry for the late answer.
Is this problem a regression or has it never worked?
I recently had to create a hotpatch to stay compatible with sway, maybe there is a protocol difference between sway and kde in the layershell implementation.

**Comment by andrei-pavel** [comment]
First time trying it, and this is the error I got, so it never worked for me.

I installed it with the package manager. [This is the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kickoff).

I will try to build it from source and will try multiple versions and will report on what I discover.

**Comment by j0ru** [comment]
v0.5.0 is the latest version before the patch, if that doesn't work, none will, so that's the only one that needs to be tested.

**Comment by j0ru** [comment]
I just updated all dependencies, try building it from main, maybe the problem has gone away by itself.

**Comment by andrei-pavel** [comment]
* `cargo install kickoff` - Still panics. The stack trace is more readable, although doesn't look that helpful.
* Built from main - panics
* Built from v0.5.1 - panics
* Built from v0.5.0 or v0.4.5:
```
$ ./target/debug/kickoff
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    26304 IOT instruction (core dumped)  ./target/debug/kickoff
EXIT 134
```
Building with `cargo build`.
```
$ cargo --version
cargo 1.66.0-nightly (73ba3f35e 2022-09-18)
EXIT 0
```
It's not out of the question that there might be something wrong with my setup. I've just switched to wayland. Still learning the ropes.

**Comment by j0ru** [comment]
It's not just you, I spend some time this afternoon to test some things for myself and I couldn't get it to work. The current incompatibility is a problem of kickoff, I'll look into it tomorrow

**Comment by j0ru** [comment]
I found the issue, if my next train has power sockets I might even be able to fix it today

**Comment by j0ru** [comment]
Welp, power but no internet, anyways pr #52 is working and will be merged after CI is finished
