### ISSUE TITLE
Removed application still appearing

### ISSUE THREAD

**Issue by kigiri** [j0ru/kickoff#60]
Recently, I replaced an application but even though it was not present anymore because of it's entry in the cache it was still always appearing in the menu.

removing the entry from `.cache/kickoff/run.cache` worked

To test:
add a non existing entry to the cache, ex:
```
99 test
```
you will see it on top every search.

We should probably ignore entries from the cache that are not present in the input

**Comment by j0ru** [comment]
Could you try the git version, it should be fixed there. You will loose your history though since format and location changed
