### ISSUE TITLE
Text is pixellated

### ISSUE THREAD

**Issue by ahelwer** [j0ru/kickoff#67]
Love this project, have been using it a lot! I'm using a 2160p display at 2x scaling in sway, and I notice the menu entry text is fairly pixelated. This is also noticeable in the demo screenshot in the readme. Do you think it would be an easy fix to get nice smooth text or would it be quite involved?

**Comment by j0ru** [comment]
It's fixed in main, unfortunately only integer scaling, since fractional scaling in wayland only exists since [one week](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/143) ^^

**Comment by ahelwer** [comment]
Great! I installed from AUR but perhaps I'll just switch to building this repo directly.

**Comment by j0ru** [comment]
Glad to help :D
You can also just switch to kickoff-git in the aur, it should always be on track with the main branch
