### ISSUE TITLE
Kickoff like rofi's drun?

### ISSUE THREAD

**Issue by Xag8031** [j0ru/kickoff#74]
**Is there a way to use kickoff like rofi's drun?**
I have a lot of apps cli apps installed on my system. I only want to show my apps like rofi's drun. I see the from file config but I don't want to have to add to a file everytime I install a new app.

**Comment by j0ru** [comment]
I thougth about implementing something like this a while ago, but came to the conclusion that parsing .desktop files (which is what drun mode in rofi is doing) is out of scope for my project. Instead I implemented the option to input from stdin. That could be use by a script parsing the desktop files and spitting out the `<name>=<command>\n` relations

**Comment by j0ru** [comment]
tbh, I don't know if something like that exists, but it shouldn't be to hard to implement

**Comment by j0ru** [comment]
Welp, now there is one: [kickoff-dot-desktop](https://github.com/j0ru/kickoff-dot-desktop)

Has to be installed by cloning and `cargo install --path .` since I'm still thinking of including it into kickoff itself

**Comment by Xag8031** [comment]
Thx man! Could not figure this out myself!
