### ISSUE TITLE
add priority for list entries

### ISSUE THREAD

**Issue by abenz1267** [j0ru/kickoff#78]
Hi,

i think it'd be good to have some form of control over the searching algorithm in form of priority. F.e. i've created https://github.com/abenz1267/hyproff and it lists Hyprland windows. 

The "problem": if i have spotify open i'd like the spotify window entry to be in top, not the executable in $PATH.

Do you think this would make sense?

Regards

**Comment by j0ru** [comment]
Hey,
just to clarify your use case, are you using kickoff with both, the `--from-stdin` and `--from-path` option?
Would it be enough if you could define a bonus score for items that are read from a different source i.e. for `--from-stdin` or would you need a per entry priority?

More control over the search parameters is something I've wanted to build for a while, especially because there is quite an old issue regarding this #30

**Comment by abenz1267** [comment]
Hi,

no, i'm just using `--from-stdin`.  I've created https://github.com/abenz1267/hyproff to provide whatever i need, but the sorting isn't always optimal.

Sorting/prioritizing needs to be specified by the provider and factored in by kickoff when searching.

Regards

**Comment by j0ru** [comment]
Okay, I think I understand now.

I'm a bit reluctant to change the format of the input because that could possibly break compatibility for people who included kickoff in their scripts, but I think a simpler approach would be to add a flag to respect the original ordering.

Cheers

**Comment by abenz1267** [comment]
yeah, that could work as well i guess. I just have to sort the source then.

**Comment by j0ru** [comment]
Perfect, I'll probably have this implemented by the end of the week

**Comment by j0ru** [comment]
Documentation was added in #81, the solution is a bit different than initially planned, but I think it works better and should give you a more fine grained control

**Comment by abenz1267** [comment]
The documentation is wrong though, you are using `%base_score` and not `$base_score`

**Comment by j0ru** [comment]
Dang it, yes of course :man_facepalming:, I think I need another coffee.
Thanks for noticing
