### ISSUE TITLE
Support keybindings

### ISSUE THREAD

**Issue by hkupty** [j0ru/kickoff#8]
Hi! First of all, thanks for the excellent launcher. I'm really pleased w/ it aesthetically and functionally.

I was wondering if it was possible to map `<C-n>` and `<C-p>` respectively for arrows down and up, but [it seems that it is not currently possible](https://github.com/j0ru/kickoff/blob/main/src/gui.rs#L278-L285). 

I'm opening the issue as a suggestion.

Thanks in advance :D

**Comment by j0ru** [comment]
Sorry for responding so late, had a lot to do lately, but over the holidays I had some time to spare and got this working!
If you build from git, you should be able to set custom keybindings in the config. You can look at the example config to learn the syntax.

**Comment by hkupty** [comment]
Amazing! Thanks for putting up the time for that. Have an excellent new year!
