### ISSUE TITLE
 'Image index, out of bounds" When text goes offscreen

### ISSUE THREAD

**Issue by fictitiousexistence** [j0ru/kickoff#80]
Hello!
Recently found your project and liked it much better than bemenu and started using it. Its great how it will show up over full-screen apps unlike bemenu.

Whenever the menu options are longer than the screen I receive the following error:
`thread 'main' panicked at 'Image index (1128, 41) out of bounds (1128, 728)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.24.5/./src/buffer.rs:946:21`

For example if I run:

`echo https://somereallylong.url.com/needtomakeuprandomstufftomaketheurlorentrylongeraaaaaaaaaaaaabbbbbbbbbbbbbbbcccccccccccccccdddddddddddddddeeeeeeeeeeeeeeeeeessss | kickoff --from-stdin --stdout`

I have a file with "bookmarks" with either long text or url's that I use (bemenu) now kickoff to run. 

Also, I swapped out bemenu for kickoff when using [Firecat53's demnu based bitwaden app](https://github.com/firecat53/bitwarden-menu).
This works perfectly, but if the saved entries are longer than the screen, the same issue occurs. 

Here's that snippet of code from the buffer.rs file:

```
    /// Gets a reference to the mutable pixel at location `(x, y)`
    ///
    /// # Panics
    ///
    /// Panics if `(x, y)` is out of the bounds `(width, height)`.
    #[inline]
    pub fn get_pixel_mut(&mut self, x: u32, y: u32) -> &mut P {
        match self.pixel_indices(x, y) {
            None => panic!(
                "Image index {:?} out of bounds {:?}",
                (x, y),
                (self.width, self.height)
            ),
            Some(pixel_indices) => <P as Pixel>::from_slice_mut(&mut self.data[pixel_indices]),
        }
    }
```

**Comment by j0ru** [comment]
Hey, thanks for taking the time!

I think I had this case handled before, but probably forgot to add the checks when rewriting the font rendering.
It's fixed in main, but I'll probably want to improve the visuals when Entries are longer than the display, so I'm leaving this Issue open

**Comment by fictitiousexistence** [comment]
@j0ru That was quick! thank you, works perfectly.
