### ISSUE TITLE
Not parsing .desktop entries in $HOME/.local/share/applications

### ISSUE THREAD

**Issue by bwyan86** [j0ru/kickoff#95]
Hi and thanks for creating this neat launcher.

I switched from using wofi which I believe more or less out-of-the-box also parses .desktop file entries found in user's ~/.local/share/applications folder.

It appears like kickoff ignores these while still honoring system-wide /usr/share/applications directory.

Is there currently any way of enabling this functionality?

Thanks!

EDIT: I thought I better also add that I'm running kickoff v. 0.7.0 on Ubuntu 22.04 installed via cargo.

**Comment by j0ru** [comment]
Hey, sorry for the late response.

Kickoff doesn't parse .desktop files by default, but it provides an interface via stdin. I've written a small demo on how to handle it with .desktop files, which you can find [here](https://github.com/j0ru/kickoff-dot-desktop). Currently, it ignores the xdg-desktop settings, parsing only the default paths. However, there is a pull request in progress to fix this issue
