### ISSUE TITLE
Delete a mistaken entry from the list

### ISSUE THREAD

**Issue by dojero** [j0ru/kickoff#96]
Absolutely great replacement for wofi. Fast doesn't describe it.

But I made a mistake and entered a partial command. Now, every time I invoke the program, one option is the partial command. Is there any way to delete it? Seems like that should be possible, but I can't figure it out.

**Comment by j0ru** [comment]
Hi,
you can manually edit `.cache/kickoff/default.csv` and delete the mistaken entry there.
