### ISSUE TITLE
Attempt to calculate the remainder with a divisor of zero

### ISSUE THREAD

**Issue by fictitiousexistence** [j0ru/kickoff#98]
Hello!

I get the message (pasted at the very bottom here) when using a clipboard program called cliphist with kickoff.

I use this command to list the clipboard contents and pipe it into kickoff:
`cliphist list | kickoff --from-stdin --stdout `
Thats when the error occurs. 

An example line from the output of cliphist looks like this:
`7127	example test`

I am able to work around it by using sed:

`cliphist list | sed 's/     / /' | kickoff --from-stdin --stdout`

Cliphist then needs to "decode it"  with the original spacing so I have to pipe it back through sed/cliphist after the above command:
`cliphist list | sed 's/     / /' | kickoff --from-stdin --stdout | sed 's/ /        /'| cliphist decode`

Is this an actual bug or should I keep "sed'ing" it or open an issue with cliphist? 

Thank you ! 

**thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', src/font.rs:116:57**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue 0x7f69a0000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@24 still attached
  zwp_primary_selection_device_manager_v1@20 still attached
  wl_data_device@23 still attached
  wl_seat@22 still attached
  wl_data_device_manager@21 still attached
  wl_registry@19 still attached
warning: queue 0x5577c34c0e80 destroyed while proxies still attached:
  wl_keyboard@18 still attached
  wl_pointer@17 still attached
  zwlr_layer_surface_v1@16 still attached
  wl_surface@15 still attached
  wl_shm_pool@14 still attached
  wl_shm_pool@13 still attached
  zwp_primary_selection_device_v1@12 still attached
  zwp_primary_selection_device_manager_v1@3 still attached
  wl_data_device@11 still attached
  wl_output@10 still attached
  zwlr_layer_shell_v1@9 still attached
  wl_seat@8 still attached
  wl_data_device_manager@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached

**Comment by fictitiousexistence** [comment]
Disregard the fact that I'm using cliphist.
It looks like its any time I pipe a file with a tab into kickoff. 

I like to format alot of files I have with tabs to get a more consistent view. 

Is there any way to support tabs in kickoff or should I just use sed?

Thank you!!!!!

**Comment by j0ru** [comment]
Soo, as always, fonts are hard and hate you. I.e. this bug only occurs with some fonts, definitely not all of them.
Also, tab behavior isn't that well documented, but the 8 spaces width seems to be the standard.
I can't really tell, how this works with variable width fonts (non-monospace), especially with width alignment, but that's not the can of worms I wan't to open right now.

For nor now, tabs will be replaced with 8 spaces, aligned to every eighth character, which only really works well with monospace fonts ¯\\_(ツ)_/¯

Feel free to test it by checking out `fix/crash-on-tabs` and running with `cargo run --release`

**Comment by fictitiousexistence** [comment]
I gave it a go!

I use "CodeNewRoman Nerd Font Mono" and got the same error message. 

I then tried "DejaVu Sans Mono" and it does not give the error. It shows the entry but with no tab or space:

ex:
"test  <tab>  test" shows as testtest

But, when you choose it, it does convert it back properly :D

**Comment by j0ru** [comment]
Are you 100% that you are on the new branch and not using the old version? The behavior you describe is consistent with the behavior before the patch, but it shouldn't be possible to fail like that anymore

When inside the project you have to run something like this:
```bash
# in the cloned project folder
git checkout fix/crash-on-tabs
echo "foo\tbar\n" | cargo run -- --from-stdin --stdout
```

**Comment by fictitiousexistence** [comment]
@j0ru 

What I did was:

`git checkout fix/crash-on-tabs`
`cargo build --release`
`cd target/release`
`cat tabs | ./kickoff --from-stdin --stdout` (tabs is a file with text with tabs)


I just tried what you suggested and got the same error. 
I did have to change:
`echo "foo\tbar\n" | cargo run -- --from-stdin --stdout`
to
`printf "foo\tbar\n" | cargo run -- --from-stdin --stdout`

as echo did not take the \t and \n (I think theres a flag to make it do so but oh well, I knew printf works for me)

I also put "foot {tab} bar" in the "tabs" file and did 

`cat  tabs | cargo run -- --from-stdin --stdout`

Same thing. :/ 
![kickoff zero issue](https://github.com/j0ru/kickoff/assets/20089581/3a0324d2-fa73-4733-b4c7-711301723e11)

**Comment by j0ru** [comment]
You are on an old version of the branch, there isn't even a division on line 116 anymore, please pull and try again.

**Comment by fictitiousexistence** [comment]
It works beautifully thank you!

I apologize, I don't know how I messed that up as I always rm -rf the entire git project on my local machine and do a fresh pull, then build.

But it worked this time :D

**Comment by j0ru** [comment]
No worries, happens to the best of us ^^

I'm gonna add a config option to set a custom tab width and merge it, probably today, maybe tomorrow

**Comment by j0ru** [comment]
Config option has to wait, I would need to restructure some of the config and that change will not happen in a minor version
