### ISSUE TITLE
Unable to start kickoff due to empty PID lock file

### ISSUE THREAD

**Issue by korrat** [j0ru/kickoff#99]
I'm using kickoff 0.7.0 as my application launcher for sway 1.8.1. Somehow, the PID lock file ended up empty, causing kickoff to check for existence of `/proc/`, which prevented new instances of kickoff from launching.

This should probably be checked separately, before checking whether the process with that PID is still running.

As a sidenote, the error message is not entirely clear: I initially checked for another instance of kickoff using `ps` but that did not show any information. Also, the lockfile prevents any other invocations, including `kickoff --help` or similar.

**Comment by j0ru** [comment]
Thanks for reporting!
